[package]
name = "stingray"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.4"
redis = { version = "0.25.4", features = ["tokio-comp"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
